### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by j8r** [FabianOvrWrt/files#9]
I propose a new app icon. If you don't like or think that severals things aren't good (like too orange), tell me, i can change and improve. I have taken the colors of the actual app icon.
![icon-32](https://cloud.githubusercontent.com/assets/6562667/4881930/3feb7cce-634f-11e4-80ce-c462101e1bda.png)
![icon-60](https://cloud.githubusercontent.com/assets/6562667/4881933/3ff4853a-634f-11e4-96c5-0dd11cd31960.png)
![icon-84](https://cloud.githubusercontent.com/assets/6562667/4881934/3ff57648-634f-11e4-8200-4ed464609998.png)
![icon-128](https://cloud.githubusercontent.com/assets/6562667/4881931/3ff39990-634f-11e4-9081-3ecd1c82f0a0.png)
![icon-284](https://cloud.githubusercontent.com/assets/6562667/4881932/3ff3ca14-634f-11e4-9164-ddb93ac4abf5.png)

[Creative Commons Attribution 4.0 International (CC BY 4.0)](http://creativecommons.org/licenses/by/4.0/)

**Comment by FabianOvrWrt** [comment]
What program have you used to make the icon?
Looks nice, but two rectangles aren't very descriptive. And the color is a bit messed up.
I moved myself from the gradients because they looked ugly on entry level phones (One Touch Fire/Fire C, ZTE Open/Open II and the ones from India).
Maybe making those two rectangles actual objects may do the trick, and revert the gradients.

**Comment by j8r** [comment]
I use GIMP. Thanks for your suggestions. Maybe, but new icons have a few gradients, principaly on the circle container, and looks nicer and polished than monochrome and solid color. That's why i try, like the actual tendency, to use a few gradient : the low end phone see no/a little difference while above phones see more pretty icon.
